# Generated by Django 2.2 on 2019-04-29 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Petiano',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('email', models.CharField(max_length=256)),
                ('mNumber', models.CharField(max_length=11)),
                ('dt_entryCourse', models.DateField()),
                ('dt_leavingCourse', models.DateField()),
                ('cpfNumber', models.CharField(max_length=11)),
                ('rgNumber', models.CharField(max_length=10)),
                ('telFix', models.CharField(max_length=10, null=True)),
                ('celNumber', models.CharField(max_length=11)),
                ('address', models.TextField()),
                ('dt_entryPet', models.DateField()),
                ('dt_leavePet', models.DateField()),
                ('functionPet', models.CharField(choices=[('T', 'Tesouraria'), ('RH', 'Relações Humanas'), ('O', 'Organização'), ('D', 'Divulgação'), ('I', 'Informática')], default='T', max_length=16)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('email', models.CharField(max_length=256)),
                ('cpfNumber', models.CharField(max_length=11)),
                ('rgNumber', models.CharField(max_length=10)),
                ('telFix', models.CharField(max_length=10, null=True)),
                ('celNumber', models.CharField(max_length=11)),
                ('address', models.TextField()),
                ('dt_entryPet', models.DateField()),
                ('dt_leavePet', models.DateField()),
                ('functionPet', models.CharField(default='Tutor', editable=False, max_length=10)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
