# Generated by Django 2.2 on 2019-05-11 02:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Caixinha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Cofre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='ContaBancaria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('edition', models.CharField(max_length=3)),
                ('dt_start', models.DateField()),
                ('dt_finish', models.DateField()),
                ('typePet', models.CharField(default='Tutor', editable=False, max_length=10)),
                ('cashier', models.FloatField(default=0.0)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=256)),
                ('email', models.CharField(max_length=256)),
                ('cpfNumber', models.CharField(max_length=11)),
                ('rgNumber', models.CharField(max_length=10)),
                ('celNumber', models.CharField(max_length=11)),
                ('address', models.TextField()),
                ('dt_entryPet', models.DateField()),
                ('dt_leavePet', models.DateField()),
                ('functionPet', models.CharField(default='Tutor', editable=False, max_length=10)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Petiano',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mNumber', models.CharField(max_length=11)),
                ('dt_entryCourse', models.DateField()),
                ('dt_leavingCourse', models.DateField()),
                ('cpfNumber', models.CharField(max_length=11)),
                ('rgNumber', models.CharField(max_length=13)),
                ('celNumber', models.CharField(max_length=11)),
                ('address', models.TextField()),
                ('dt_entryPet', models.DateField()),
                ('dt_leavePet', models.DateField()),
                ('functionPet', models.CharField(choices=[('T', 'Tesouraria'), ('RH', 'Relações Humanas'), ('O', 'Organização'), ('D', 'Divulgação'), ('I', 'Informática')], default='T', max_length=16)),
                ('debt', models.FloatField(default=0.0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoPetiano',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateField()),
                ('value', models.FloatField(default=0.0)),
                ('main_reason', models.CharField(max_length=30)),
                ('description', models.TextField(null=True)),
                ('from_place', models.CharField(choices=[('PB', 'Próprio Bolso'), ('CA', 'Caixinha'), ('CO', 'Cofre'), ('CB', 'Conta Bancária')], default='CA', max_length=16)),
                ('to_place', models.CharField(choices=[('PB', 'Próprio Bolso'), ('CA', 'Caixinha'), ('CO', 'Cofre'), ('CB', 'Conta Bancária')], default='CA', max_length=16)),
                ('petiano', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Petiano')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoEvento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateField()),
                ('value', models.FloatField(default=0.0)),
                ('main_reason', models.CharField(max_length=30)),
                ('description', models.TextField(null=True)),
                ('from_place', models.CharField(choices=[('PB', 'Próprio Bolso'), ('CA', 'Caixinha'), ('CO', 'Cofre'), ('CB', 'Conta Bancária')], default='CA', max_length=16)),
                ('to_place', models.CharField(choices=[('PB', 'Próprio Bolso'), ('CA', 'Caixinha'), ('CO', 'Cofre'), ('CB', 'Conta Bancária')], default='CA', max_length=16)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Evento')),
                ('petiano', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Petiano')),
            ],
        ),
    ]
