# Generated by Django 2.2 on 2019-04-29 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('edition', models.CharField(max_length=3)),
                ('dt_start', models.DateField()),
                ('dt_finish', models.DateField()),
                ('typePet', models.CharField(default='Tutor', editable=False, max_length=10)),
                ('cashier', models.FloatField(default=0.0)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='petiano',
            name='debt',
            field=models.FloatField(default=0.0),
        ),
    ]
