# Generated by Django 2.2 on 2019-05-22 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190522_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='typePet',
            field=models.CharField(choices=[('Extensão', 'Extensão'), ('Ensino', 'Ensino')], default='Extensão', max_length=10),
        ),
    ]
