# Generated by Django 2.2 on 2019-04-30 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190429_2343'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caixinha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Cofre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='ContaBancaria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoPetiano',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateField()),
                ('value', models.FloatField(default=0.0)),
                ('main_reason', models.CharField(max_length=30)),
                ('description', models.TextField(null=True)),
                ('from_place', models.CharField(choices=[('PB', 'Próprio Bolso'), ('CA', 'Caixinha'), ('CO', 'Cofre'), ('CB', 'Conta Bancária')], default='CA', max_length=16)),
                ('to_place', models.CharField(choices=[('PB', 'Próprio Bolso'), ('CA', 'Caixinha'), ('CO', 'Cofre'), ('CB', 'Conta Bancária')], default='CA', max_length=16)),
                ('petiano', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Petiano')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoEvento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('petiano', models.CharField(max_length=50)),
                ('dt_created', models.DateField()),
                ('value', models.FloatField(default=0.0)),
                ('main_reason', models.CharField(max_length=30)),
                ('description', models.TextField(null=True)),
                ('from_place', models.CharField(choices=[('PB', 'Próprio Bolso'), ('CA', 'Caixinha'), ('CO', 'Cofre'), ('CB', 'Conta Bancária')], default='CA', max_length=16)),
                ('to_place', models.CharField(choices=[('PB', 'Próprio Bolso'), ('CA', 'Caixinha'), ('CO', 'Cofre'), ('CB', 'Conta Bancária')], default='CA', max_length=16)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Evento')),
            ],
        ),
    ]
