# Generated by Django 2.2 on 2019-04-30 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_caixinha_cofre_contabancaria_historicoevento_historicopetiano'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicoevento',
            name='petiano',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Petiano'),
        ),
    ]
